theme: jekyll-theme-minimal
title: Amaro
description: Welcome to my personal website! Here you'll find all sort of information about me and my projects!
logo: https://pbs.twimg.com/profile_images/1357849612619546631/A6AhwxmB_400x400.jpg
color: #2bff6b
